services:

  accounting-db-server:
    image: postgres:14.0-alpine
    # restart: unless-stopped
    container_name: accounting-db-server
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
    environment:
      POSTGRES_DB: accounting-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGPORT: 5433
    volumes:
      - postgres-db-vol:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - acc-network

  accounting-service:
    image: accounting-service
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: accounting-service
    # restart: unless-stopped
    depends_on:
      - accounting-db-server
    ports:
      - "8080:8080"
    networks:
      - acc-network
volumes:
  postgres-db-vol:
networks:
  acc-network:
    driver: bridge