spring:
  application:
    name: accounting-service

# Database Config Settings
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://accounting-db-server:5433/accounting-db?currentSchema=accounting
    username: postgres
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Database migration config settings
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://accounting-db-server:5433/accounting-db
    user: postgres
    password: postgres123
    schemas: accounting
    baseline-on-migrate: true
    baseline-version: 0
    out-of-order: true
    validate-on-migrate: true
    validate-migration-naming: true
