spring:
  application:
    name: accounting-service

# Database Config Settings
spring:
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://accounting-db-server:5433/db-accounting?currentSchema=accounting
    username: postgres
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
